#!/bin/bash
# bups is short for backups
# $BACKUP is an enviromental variable that holds the backup directory

bupsloc="$BACKUP/projects-archive"
dtstamp=$(date +"%Y-%m-%d-%H%M")
bupsnum=$(ls $bupsloc | wc -w)

# Keep at maximum 14 (~2 weeks worth of) backups
if [ $bupsnum -eq 14 ]
then
	rm -rf $(ls $bupsloc -tr | head -1)
fi

rsync -a -r --quiet $HOME/projects $bupsloc/$dtstamp
