#!/bin/bash
# Syntax:
# $ convert format toFormat
# Example to convert all .wav files in current directory to .mp3:
# $ convert wav mp3

for i in *.$1; do
	ffmpeg -i $i -vn -ar 44100 -ac 2 -b:a 192k $(echo $i | cut -d"."  -f1).$2 > /dev/null &&\
	printf "Succesfully converted $i from $1 to $2 \n" ||\
	printf "Couldn't convert $i to from $1 to $2 \n"
done
