#!/bin/bash

if [ -z "$1" ]
then
    printf "Please specify a git operation\n Example: gitall pull"
    exit 1
fi

if [ -z "$2" ]
then
	dir=$(pwd)
else
	dir=$2
fi

for subdir in $dir/*
do
    printf "$subdir: "
    git -C ./$subdir $1 || exit 2
done
