#!/bin/bash

# Sync files to local directory
# .config/ files
rsync -r --delete ~/.config/i3/* ~/projects/dotfiles/i3
rsync -r --delete ~/.config/polybar/* ~/projects/dotfiles/polybar
rsync -r --delete ~/.config/cava/* ~/projects/dotfiles/cava
rsync -r --delete ~/.config/gtk-2.0/* ~/projects/dotfiles/gtk-2.0
rsync -r --delete ~/.config/gtk-3.0/* ~/projects/dotfiles/gtk-3.0
rsync -r --delete ~/.config/dunst/* ~/projects/dotfiles/dunst
rsync -r --delete ~/.config/termite/* ~/projects/dotfiles/termite

# ~ files
rsync ~/.bashrc ~/projects/dotfiles/other
rsync ~/.bash_profile ~/projects/dotfiles/other
rsync ~/.bash_logout ~/projects/dotfiles/other
rsync ~/.gtkrc-2.0 ~/projects/dotfiles/other
rsync ~/.profile ~/projects/dotfiles/other
rsync ~/.vimrc ~/projects/dotfiles/other
rsync ~/.xinitrc ~/projects/dotfiles/other
rsync ~/.Xresources ~/projects/dotfiles/other


# git procedures
git -C ~/projects/dotfiles add -A
git -C ~/projects/dotfiles commit
git -C ~/projects/dotfiles push
