#!/bin/bash

# Sync files to local directory
# .config/ files
rsync -r --delete $HOME/.config/i3 $HOME/projects/dotfiles
rsync -r --delete $HOME/.config/polybar $HOME/projects/dotfiles
rsync -r --delete $HOME/.config/cava $HOME/projects/dotfiles
rsync -r --delete $HOME/.config/gtk-2.0 $HOME/projects/dotfiles
rsync -r --delete $HOME/.config/gtk-3.0 $HOME/projects/dotfiles
rsync -r --delete $HOME/.config/dunst $HOME/projects/dotfiles
rsync -r --delete $HOME/.config/termite $HOME/projects/dotfiles

# $HOME files
rsync $HOME/.bashrc $HOME/projects/dotfiles/other/
rsync $HOME/.bash_profile $HOME/projects/dotfiles/other/
rsync $HOME/.bash_logout $HOME/projects/dotfiles/other/
rsync $HOME/.gtkrc-2.0 $HOME/projects/dotfiles/other/
rsync $HOME/.vimrc $HOME/projects/dotfiles/other/
rsync $HOME/.xinitrc $HOME/projects/dotfiles/other/
rsync $HOME/.Xresources $HOME/projects/dotfiles/other/

# git procedures
git -C $HOME/projects/dotfiles add -A
git -C $HOME/projects/dotfiles commit
git -C $HOME/projects/dotfiles push
