#!/bin/bash
# Works best for simple (usually personal) projects where a general push doesn't cause any conflicts
# For maximum automation it is recommended to use SSH to push to the remote repository

if [ -z "$1" ]
then
	dir=$(pwd)
else
	dir=$1
fi

# git procedures
git -C $dir pull
git -C $dir add -A
git -C $dir commit
git -C $dir push
