#!/bin/bash

neofetch --disable uptime local_ip public_ip

cal -3 -m
echo ""

# Print todo list with numbering
echo "${BOLD}${C6}Todo List${RESET}"
if [ "$(wc -l ~/.todo | cut -d" " -f1)" -gt 0 ]; then
	nl ~/.todo
else
    echo "There is nothing to do."
fi

echo ""

# Check # of available updates
if ! updates=$(checkupdates 2> /dev/null | wc -l ); then
    updates=0
fi

if [ "$updates" -gt 0 ]; then
    echo "${BOLD}${C6}System status:${RESET} $updates updates ready"
else
    echo "${BOLD}${C6}System up-to date${RESET}"
fi
echo ""
